/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FerashaSlugRouteImport } from './routes/ferasha.$slug'
import { Route as AuthenticatedMyFerashaRouteImport } from './routes/_authenticated/my-ferasha'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedListingsNewRouteImport } from './routes/_authenticated/listings.new'
import { Route as AuthenticatedListingsIdRouteImport } from './routes/_authenticated/listings.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FerashaSlugRoute = FerashaSlugRouteImport.update({
  id: '/ferasha/$slug',
  path: '/ferasha/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyFerashaRoute = AuthenticatedMyFerashaRouteImport.update({
  id: '/my-ferasha',
  path: '/my-ferasha',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListingsNewRoute =
  AuthenticatedListingsNewRouteImport.update({
    id: '/listings/new',
    path: '/listings/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingsIdRoute = AuthenticatedListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/my-ferasha': typeof AuthenticatedMyFerashaRoute
  '/ferasha/$slug': typeof FerashaSlugRoute
  '/listings/$id': typeof AuthenticatedListingsIdRoute
  '/listings/new': typeof AuthenticatedListingsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/my-ferasha': typeof AuthenticatedMyFerashaRoute
  '/ferasha/$slug': typeof FerashaSlugRoute
  '/listings/$id': typeof AuthenticatedListingsIdRoute
  '/listings/new': typeof AuthenticatedListingsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/my-ferasha': typeof AuthenticatedMyFerashaRoute
  '/ferasha/$slug': typeof FerashaSlugRoute
  '/_authenticated/listings/$id': typeof AuthenticatedListingsIdRoute
  '/_authenticated/listings/new': typeof AuthenticatedListingsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account'
    | '/my-ferasha'
    | '/ferasha/$slug'
    | '/listings/$id'
    | '/listings/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account'
    | '/my-ferasha'
    | '/ferasha/$slug'
    | '/listings/$id'
    | '/listings/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/account'
    | '/_authenticated/my-ferasha'
    | '/ferasha/$slug'
    | '/_authenticated/listings/$id'
    | '/_authenticated/listings/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FerashaSlugRoute: typeof FerashaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferasha/$slug': {
      id: '/ferasha/$slug'
      path: '/ferasha/$slug'
      fullPath: '/ferasha/$slug'
      preLoaderRoute: typeof FerashaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-ferasha': {
      id: '/_authenticated/my-ferasha'
      path: '/my-ferasha'
      fullPath: '/my-ferasha'
      preLoaderRoute: typeof AuthenticatedMyFerashaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings/new': {
      id: '/_authenticated/listings/new'
      path: '/listings/new'
      fullPath: '/listings/new'
      preLoaderRoute: typeof AuthenticatedListingsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings/$id': {
      id: '/_authenticated/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof AuthenticatedListingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedMyFerashaRoute: typeof AuthenticatedMyFerashaRoute
  AuthenticatedListingsIdRoute: typeof AuthenticatedListingsIdRoute
  AuthenticatedListingsNewRoute: typeof AuthenticatedListingsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedMyFerashaRoute: AuthenticatedMyFerashaRoute,
  AuthenticatedListingsIdRoute: AuthenticatedListingsIdRoute,
  AuthenticatedListingsNewRoute: AuthenticatedListingsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FerashaSlugRoute: FerashaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
